version: '3'
services:
  node_api:
    build: .
    ports:
      - "6002:6002"
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    env_file:
      - ./config/.env
    network_mode : "host"
